### ISSUE TITLE
Make contest leaderboard searchable for a given username

### ISSUE THREAD

**Issue by bzcode01** [Being-Zero/mentorpick-issues#10]
Refer a contest leaderboard,
https://mentorpick.com/new/leaderboard/62a2f2aa518edb3ceeaba379/BeingZero-Weekly-Contest-1/1655389800000

There is no option to search for a particular username to check user's participation.

**Comment by mitesh-bz** [comment]
Mentorpick's latest version has an improved UI for leaderboard with ability to search users participation.
