### ISSUE TITLE
spelling correction on Home page of the Mentorpick

### ISSUE THREAD

**Issue by kaushikkumarbz** [Being-Zero/mentorpick-issues#11]
![WhatsApp Image 2022-07-28 at 2 35 47 PM](https://user-images.githubusercontent.com/65885903/182300657-cb126514-8514-46b9-9ee6-cf1277dcd564.jpeg)
![WhatsApp Image 2022-07-28 at 2 35 46 PM](https://user-images.githubusercontent.com/65885903/182300670-2063d812-fc18-4425-83e8-329912a8d144.jpeg)

**Comment by mitesh-bz** [comment]
Mentorpick's latest version has an improved UI with fixes for this issue.
