### ISSUE TITLE
Unable to upload large testcases for the contest questions in mentorpick

### ISSUE THREAD

**Issue by nithyabz** [Being-Zero/mentorpick-issues#12]
When Uploaded, it is showing wrong answer for that particular test case

**Comment by nithyabz** [comment]
> When Uploaded, it is showing wrong answer for that particular test case

This issue was resolved recently, again the same issue is there

**Comment by mitesh-bz** [comment]
Since most external sites support the same size for test cases as mentorpick, we don't plan to support larger sizes.
