### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by jithu-jithendra-2003** [Being-Zero/mentorpick-issues#13]
**Is your feature request related to a problem? Please describe.**
Yes ,Because i have been rejected while accessing the courses.

**Describe the solution you'd like**
Please provide the option to change the name so that, i can change my name to my college id, so that our college management can accept our request by seeing the id number.

**Comment by mitesh-bz** [comment]
Hi @jithu-jithendra-2003 
Thank you for reaching out to us. Currently we do not have plan to allow users to modify their username.

Regarding access to course, request you to get in touch with the BeingZero Trainer/Mentor visiting your college. They will assist you in getting signed up to the right course.
