### ISSUE TITLE
Copy Button for Example Input

### ISSUE THREAD

**Issue by akhilsunku12** [Being-Zero/mentorpick-issues#14]
Please privide copy button for Example inputs. It's help us to copy the input in a faster way.

**Comment by mitesh-bz** [comment]
Thank you for requesting the feature, we have added it to our backlog.

**Comment by mitesh-bz** [comment]
@akhilsunku12 - We have deployed a new feature where the sample inputs can be populated via a drop down menu. Thus eliminating the need for copy pasting the code.

Keep using and reporting issues/features to improve the experience.
