### ISSUE TITLE
It is not allowing to change the username if it is set once..I think that should be looked at.

### ISSUE THREAD

**Issue by PallaviReddyV** [Being-Zero/mentorpick-issues#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mitesh-bz** [comment]
@PallaviReddyV - thank you for creating this feature request. Currently we do not allow users to change their username. In case you need it changed, please reach out to the Being Zero mentor, teacher or coordinator and they will be able to update it for you.
