### ISSUE TITLE
Regarding "Ask a doubt "  screen

### ISSUE THREAD

**Issue by hemasreej** [Being-Zero/mentorpick-issues#17]
**Describe the bug**
1.When pressing "open the editor" -  then it is giving some random alphanumeric words but not the exact code which was saved
2. There is no submit button "In ask a doubt" screen
**To Reproduce**
1. Go to 'submissions'
2. Click on 'ask a doubt '
3. write a query 
4. No submit button

**Expected behavior**
need to have a submit button in "ask a doubt" screen and when pressing open in editor of previously written code, should get the previous saved code
**Screenshots**
![image](https://github.com/Being-Zero/mentorpick-issues/assets/92966088/09cc769f-0c35-42a9-92bc-8696f36402fb)
![image](https://github.com/Being-Zero/mentorpick-issues/assets/92966088/292cb322-1518-4977-bb81-2f545488f720)

**Desktop (please complete the following information):**

**Comment by mitesh-bz** [comment]
Thanks for @hemasreej  creating the bug.
1. The issue with "Open in Editor" has been fixed and it now works as expected.
2. The Ask Doubt page, currently only supports copying the text and pasting in your respective WhatsApp group. So use the Copy button on top right corner, and all the text is available in clipboard to be shared with your mentors/friends.
