### ISSUE TITLE
Small feature

### ISSUE THREAD

**Issue by JithinReddy1445** [Being-Zero/mentorpick-issues#18]
Just a simple feature so that we can change our username . We cannot change when it was changed once so it might be a slight problem. Atleast there is timer cooldown after how many days u can change the username again

**Comment by mitesh-bz** [comment]
Thanks for filing the feature request. As of now, username change is Admin only option. 
Allowing users to themselves change the name is part of our roadmap, but I do not have a definite timeline to when it will be implemented.

You can connect with your mentor/trainer to get it updated for the time being.
