### ISSUE TITLE
Contest Submissions Tab Scroll Bug

### ISSUE THREAD

**Issue by KanniShashankh** [Being-Zero/mentorpick-issues#19]
**Describe the bug**
The Page cannot be scrolled to view the whole code

**To Reproduce**
1. Go to CourseV2 Contest 
2. Click on Submissions Tab
3. Click on any past submission with a long code

**Expected behavior**
The page should be able to scrollable to the bottom so that users can view the whole code.

**Screenshots**
<img width="1470" alt="Screenshot 2023-07-23 at 5 30 53 PM" src="https://github.com/Being-Zero/mentorpick-issues/assets/63902267/8f323de4-164a-4f8a-825e-3392079c530a">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by mitesh-bz** [comment]
Thanks for reporting the issue @KanniShashankh We will update this issue, once the fix is deployed.

**Comment by mitesh-bz** [comment]
@KanniShashankh This is fixed.
