### ISSUE TITLE
Issue on Tracking the Question

### ISSUE THREAD

**Issue by 190330249** [Being-Zero/mentorpick-issues#2]
When a person(non-admin) clicks on a question inside a class , it is showing a blank page instead of the question.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/77140388/173305199-8e3cf530-22eb-4853-b1cf-4018f5c19bac.png">

**Comment by kaushikkumarbz** [comment]
Solved the issue of problem statement not showing up in new UI.
Resolve the issue Or Let us know if it still exists
