### ISSUE TITLE
Number Of Questions

### ISSUE THREAD

**Issue by Satya-Sreekar** [Being-Zero/mentorpick-issues#20]
**Describe the bug**
When viewing the questions tab from a question the no of questions solved is becoming 0 in every category

**To Reproduce**
1. Go to a contest
2. Go to the Questions tab
3. Click on any of the questions 
4. Click on the topic Title to go to the questions

**Expected behavior**
All the topics have 0 as the no of questions solved
**Screenshots**
![image](https://github.com/Being-Zero/mentorpick-issues/assets/84071421/8d095a83-4e18-4fcb-b81f-6b8e55120050)

**Desktop (please complete the following information):**
 - OS: Windows 11 pro
 - Browser chrome
 - Version 115.0.5790.110 (Official Build) (64-bit)

**Comment by kaushikkumarbz** [comment]
Thanks for filing the issue. 
It is fixed now.
