### ISSUE TITLE
Logged out from Mentorpick Alert does not auto close.

### ISSUE THREAD

**Issue by KanniShashankh** [Being-Zero/mentorpick-issues#21]
**Describe the bug**
The Logged out alert does not auto close

**To Reproduce**
1. Log Out
2. Click Login again without changing any tabs

**Expected behavior**
Should ideally autoclose

**Screenshots**
<img width="491" alt="Screenshot 2023-08-22 at 10 16 34 PM" src="https://github.com/Being-Zero/mentorpick-issues/assets/63902267/0dce9760-8340-402b-b44b-553813afb795">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by mitesh-bz** [comment]
@KanniShashankh Thank you for reporting this. We will update once fixed.

**Comment by mitesh-bz** [comment]
> @KanniShashankh Thank you for reporting this. We will update once fixed.

This is fixed.
