### ISSUE TITLE
Leader Board Position

### ISSUE THREAD

**Issue by HARSHA-Z1** [Being-Zero/mentorpick-issues#23]
I had multiple solutions for a question, as soon as I submitted all the multiple solutions of the same question then mentorpick placed me at 3 position even though I was first to solve all the questions.
Here mentorpick is sorting the leaderboard based on the last accepted rather than first accepted of a particular solution

**Comment by kaushikkumarbz** [comment]
Please share the link of the contest and your Mentorpick username.

**Comment by mitesh-bz** [comment]
Closing due to lack of response. As of now, we sort leaderboard based on the first AC submission.
