### ISSUE TITLE
run and submit access

### ISSUE THREAD

**Issue by CharanMoigari** [Being-Zero/mentorpick-issues#24]
Plz give the access to submit the problems of contests after contest ends.So that everyone can practice the question which they didnt got during the contest.

**Comment by mitesh-bz** [comment]
> Plz give the access to submit the problems of contests after contest ends.So that everyone can practice the question which they didnt got during the contest.

Certain contests do not allow submissions post the end time. However most practice and public contests do allow submissions along with editorials to help students up solve.
