### ISSUE TITLE
Pasting within the editor

### ISSUE THREAD

**Issue by KVKcodes** [Being-Zero/mentorpick-issues#26]
It is extremely frustrating when you cannot paste boiler code, but the editor is so restrictive that you cannot paste values from the same editor. Pasting within the same editor has been achieved by many online editors and coding platforms like GeeksForGeeks.

I can use the alternatives such as duplicating a line or moving a line top or bottom using the _option_ key for mac. But it doesn't cater to all use cases.

**Comment by KVKcodes** [comment]
I understand that plagiarism is a concern for ZeroOne but I do not think just preventing students from using the copy paste function within the editor is not going to hinder plagiarism by large. 

It is especially frustrating when you want to query in the internet what is wrong with your code or when you want to paste boiler, so it is better to at least allow the copy function or the paste function. Or at least enabling copy paste within the editor.

**Comment by mitesh-bz** [comment]
@KVKcodes - Copy/Paste is allowed (or disallowed) based on contest type. Some practice contests do have copy/paste enabled in the editor. However for a large number of contests, it is disabled.
We understand the frustration for smart coders, however our observation has been that given an option, students indulge in blindly copy pasting answers just to show progress. This does not fully eliminate plagiarism, but makes it harder.
