### ISSUE TITLE
shortcuts for run and submit operations

### ISSUE THREAD

**Issue by sravan7684** [Being-Zero/mentorpick-issues#29]
it very frustrating to always go and click the run button in the below ........instead of that please include for like: crtl + enter , shift+enter ,etc so that it will be more simple to practice questions fastly.

**Comment by mitesh-bz** [comment]
@sravan7684 Thank you for requesting this feature. We have added it in our backlog and will update once add to the website.

**Comment by mitesh-bz** [comment]
@sravan7684 Key board shortcuts added for Run (Ctrl + `) Submit (Ctrl + Enter) and Reset (Ctrl + Shift + 1) code options in the IDE.
