### ISSUE TITLE
Formatting issue while writing blogs

### ISSUE THREAD

**Issue by 19WH1A0524** [Being-Zero/mentorpick-issues#3]
Indentation and formatting is getting changed every time something is pasted while creating the blogs,
Not able to use tab for long spaces 

Steps to produce:
After creating the blog with proper spacing and saving it. There is a difference in spacing in the edit view, and saved view. 

Edit view: 
![image](https://user-images.githubusercontent.com/84609254/173524946-f2ef1844-da33-40b1-966f-b0535733b1d3.png)
Saved view: 
![image](https://user-images.githubusercontent.com/84609254/173525123-d9d58757-5840-412d-92b9-b3ec40dfb71c.png)

Expected performance:
Edit view and saved view need to be the same and while editing more flexible formatting techniques can be incorporated

**Comment by mitesh-bz** [comment]
@19WH1A0524  Can this be reproduced in the new UI?

**Comment by mitesh-bz** [comment]
Issue with v1, which is archived.
