### ISSUE TITLE
Sort Latest contests on top, in Course contest page.

### ISSUE THREAD

**Issue by KanniShashankh** [Being-Zero/mentorpick-issues#30]
Currently the oldest contest appears first. 

**Describe the solution you'd like**
It would be better if the latest contests appear on top, in the course contests page

<img width="1470" alt="Screenshot 2024-03-06 at 11 21 27 AM" src="https://github.com/Being-Zero/mentorpick-issues/assets/63902267/1ef36acf-b66c-4ee6-8672-3c3d9102c1c1">

**Comment by mitesh-bz** [comment]
Thanks @KanniShashankh for requesting this change. We will review it and add it to our backlog.

**Comment by hm32005** [comment]
This feature should definitely be prioritized. It's a bad user experience not to be able to see the latest contests first.

**Comment by hm32005** [comment]
Great job @mitesh-bz! I'm no longer with the BeingZero but I'm sure this'll help current course takers a lot.
