### ISSUE TITLE
View Count in My doubt Section 

### ISSUE THREAD

**Issue by BalajiYaswanth18** [Being-Zero/mentorpick-issues#31]
Every time i open the doubt that i submitted the view count is getting increased instead this has to be increased only once that too only when instructors open that particular doubt 

1. Submit a doubt 
2. Click on the doubt 
3. Come back and see view count

Expected behavior: 
Would be great if it increases only once for each profile instead of getting increased every single time

 - OS: MacOs
 - Browser : Chrome

**Comment by mitesh-bz** [comment]
@BalajiYaswanth18 Thank you for reporting this bug. We have removed the View and Upvote counts from the display as they are misleading.
