### ISSUE TITLE
Remove autocomplete prompts

### ISSUE THREAD

**Issue by hm32005** [Being-Zero/mentorpick-issues#32]
**Is your feature request related to a problem? Please describe.**
Autocomplete usually generates incorrect/irrelevant prompts that's frustrating to avoid. Pressing enter accepts the prompt while that's not the standard behaviour in other IDEs.

**Describe the solution you'd like**
I've only coded in Python on the platform, so I'm not aware of the utility for other coding languages. However, in a real interview setting, the platform does not generate any autocomplete suggestions. So it would be best to get rid of the suggestions or at least provide an option to users if they would like to toggle the feature.

**Describe alternatives you've considered**
1. Provide a toggle setting to enable/disable autocomplete suggestions.

**Comment by mitesh-bz** [comment]
Thank you for requesting this feature and apologies for delayed response. We have added it to our backlog.

**Comment by mitesh-bz** [comment]
@hm32005  Latest release has a toggle button above IDE to manage Auto Completion feature.
<img width="881" alt="WhatsApp Image 2024-12-14 at 19 15 58" src="https://github.com/user-attachments/assets/161fc18d-c2f7-46bf-b9e1-d24829b9b4cd" />
