### ISSUE TITLE
Ability to close unsolved doubts

### ISSUE THREAD

**Issue by hm32005** [Being-Zero/mentorpick-issues#34]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to go through a long list of unsolved doubts to identify which ones still need to be addressed.

**Describe the solution you'd like**
Give users the ability to close their own doubts if they've found a solution elsewhere. They can provide a comment and close the doubt. They can create a new doubt for the same problem as and when necessary.

**Comment by mitesh-bz** [comment]
Thank you for requesting this feature and apologies for delayed response. We will add it to out backlog.

**Comment by mitesh-bz** [comment]
@hm32005 - This feature is available now.
