### ISSUE TITLE
withdraw of course request

### ISSUE THREAD

**Issue by rishikeshh09** [Being-Zero/mentorpick-issues#35]
1.I've accidentally requested a course of some other college, that's not in my phase. and there is no way to withdraw that request. 

It shows on my profile as pending.. 

please add a feature to withdraw requests.

2. while asking doubts we cannot mark a doubt as resolved unless it is replied by some mentor. there are few doubts which very old and are not getting reply by mentors or maybe they have been solved before a mentor can reply so it my profile it shows as unresolved

please add a feature so that doubts can be mark resolved even when a mentor has not replied to that doubt

**Comment by mitesh-bz** [comment]
@rishikeshh09 - Thank you for reporting the improvements and apologies for delayed response.

We will add a button to cancel a request. In the mean time, if you can share the course names and your mentorpick user name, we will revoke the pending requests.

We will also add buttons to mark solved w/o a response. However, can you share the doubt links here or in the Whatsapp group or with your mentor/instructor, we will get it reviewed as why they were not responded.

**Comment by mitesh-bz** [comment]
@rishikeshh09 - Both these features are available.
