### ISSUE TITLE
Showing accepted in mentor pick contests when we run code even if answer is wrong

### ISSUE THREAD

**Issue by h190330190** [Being-Zero/mentorpick-issues#8]
When we hit on run code in contests, it runs against some given input and if no compilation errors, it shows "output: accepted" and our code output below, this happens even if our output is wrong according to the given test case. Many students are getting confused thinking they're code is correct seeing accepted.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/78244925/173993763-e1bc99a1-e348-42f1-8ef5-6b3cc5792447.png">

Expected performance:
"Output: Accepted" should be shown after comparing submitted output to expected output OR
Instead of "Output: Accepted" it can be changed to "Output"

**Comment by mitesh-bz** [comment]
Mentorpick's latest version has an improved UI for problem submissions.
