### ISSUE TITLE
Submit-Button Run-Button hided behind the fixed bottom 

### ISSUE THREAD

**Issue by 1a1242** [Being-Zero/mentorpick-issues#9]
**Issue** 
Few students are unable to scroll the screen and are not able to see the submit and run buttons.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/85673838/174939890-81f1e6da-2fc2-428f-bd43-9a671cdc9d6b.png">
**Occurrence**
It is depended upon the screen resolution.
**Expected** 
It is expected to auto adjust the scroll depending on the screen resolution.

**Comment by mitesh-bz** [comment]
Mentorpick's latest version has an improved UI for problem submission.
